services:
  - type: web
    name: zebaish-menu
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: node server.cjs
    publishDir: dist
    envVars:
      - key: NODE_VERSION
        value: 18