# Generated by Django 5.1.7 on 2026-08-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('gstin', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('next_invoice_no', models.IntegerField(default=1)),
                ('default_tax_type', models.CharField(default='CGST+SGST', max_length=20)),
                ('default_brand', models.CharField(default='Zebaish', max_length=50)),
                ('auto_delete_pdf_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='inventory.company')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('book_no', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_doc_type', models.CharField(default='GST', max_length=20)),
                ('customer_doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('consignee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('consignee_address', models.TextField(blank=True, null=True)),
                ('consignee_state', models.CharField(blank=True, max_length=100, null=True)),
                ('consignee_state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('consignee_doc_type', models.CharField(default='GST', max_length=20)),
                ('consignee_doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('consignee_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('transport_name', models.CharField(blank=True, max_length=200, null=True)),
                ('transport_mode', models.CharField(default='By Road', max_length=50)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gr_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gr_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_type', models.CharField(choices=[('IGST', 'IGST (Inter-State)'), ('CGST+SGST', 'CGST + SGST (Intra-State)'), ('NIL', 'NIL / Exempt')], default='CGST+SGST', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('freight_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('items_data', models.JSONField(default=list)),
                ('brand', models.CharField(choices=[('ATC', 'ATC'), ('Zebaish', 'Zebaish Caterers'), ('Signature Spread', 'Signature Spread')], default='Zebaish', max_length=50)),
                ('is_corrected', models.BooleanField(default=False)),
                ('original_invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('correction_date', models.DateField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True, null=True)),
                ('corrected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('correction_count', models.IntegerField(default=0)),
                ('is_sent_whatsapp', models.BooleanField(default=False)),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('package', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_code', models.CharField(max_length=20)),
                ('unit', models.CharField(choices=[('BOX', 'BOX'), ('KG', 'KG'), ('PCS', 'PCS'), ('LTR', 'LTR'), ('DOZEN', 'DOZEN'), ('NOS', 'NOS')], default='BOX', max_length=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doc_type', models.CharField(choices=[('GST', 'GST No'), ('PAN', 'PAN Card'), ('Aadhar', 'Aadhar No'), ('NONE', 'None')], default='GST', max_length=10)),
                ('doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(default='user', max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='item',
        ),
        migrations.DeleteModel(
            name='MenuSubmission',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='original_invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='original_invoice',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='gst_number',
            new_name='doc_number',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_date',
            new_name='po_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='doc_type',
            field=models.CharField(choices=[('GST', 'GST No'), ('PAN', 'PAN Card'), ('Aadhar', 'Aadhar No'), ('NONE', 'None')], default='GST', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], default='cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_no',
            field=models.CharField(default='PO-0001', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='inventory.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='inventory.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappqueue',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_queues', to='inventory.invoice'),
        ),
        migrations.DeleteModel(
            name='DeliveryChallan',
        ),
        migrations.DeleteModel(
            name='GoodsReceipt',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoice',
        ),
        migrations.DeleteModel(
            name='SalesInvoice',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
