# Generated by Django 5.1.7 on 2026-08-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_customer_id_alter_item_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=5, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_type', models.CharField(choices=[('IICC', 'IICC Customer'), ('NonIICC', 'Non-IICC Customer')], default='IICC', max_length=10)),
                ('religion', models.CharField(choices=[('M', 'Muslim'), ('NM', 'Non-Muslim')], default='M', max_length=2)),
                ('greeting_used', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('FollowUp', 'Follow Up'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
